[package]
name = "gof-ui"
version = "0.1.0"
edition = "2021"

[lib]
name = "gof_lib"
path = "./src/lib.rs"

[[bin]]
name = "gof"
path = "./src/main.rs"

[profile.dev]
opt-level = 1

[dependencies]
crossterm = "0.23"

log = "0.4"
simplelog = "0.11"

ropey = "1.3"
