[package]
<<<<<<< HEAD
name = "rust-text-editor"
=======
name = "gof-ui"
>>>>>>> 13b061f (Beginning of re-write using custom ui framework)
version = "0.1.0"
edition = "2021"

[lib]
<<<<<<< HEAD
name = "gof_lib"
path = "./src/lib.rs"

[[bin]]
name = "gof"
path = "./src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# tui = "0.17"
# crossterm = "0.22"

termion = "1.5"
tui = { version = "0.17", default-features = false, features = [ "termion" ] }

ropey = "1.3"
=======
path = "./src/lib.rs"

[[bin]]
name = "gof-ui-bin"
path = "./src/main.rs"

[profile.dev] 
opt-level = 1
lto = "thin"

[profile.release]
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23"
>>>>>>> 13b061f (Beginning of re-write using custom ui framework)

log = "0.4"
simplelog = "0.11"

<<<<<<< HEAD
toml = "0.5"
regex = "1.5"

strum = "0.23"
strum_macros = "0.23"
=======
ropey = "1.3"
>>>>>>> 13b061f (Beginning of re-write using custom ui framework)
