[global]
NormalMode      = "esc"
MoveLeft        = "left"
MoveDown        = "down"
MoveUp          = "up"
MoveRight       = "right"

[normal]
MoveLeft        = "h"
MoveDown        = "j"
MoveUp          = "k"
MoveRight       = "l"
InsertMode      = "i"
Append          = "a"
AppendLineEnd   = "A"
InsertLineStart = "I"
ScrollMode      = "n"
Write           = "W"

[scroll]
ScrollDown      = "j"
ScrollUp        = "k"
PageDown        = "J"
PageUp          = "K"
TopOfBuffer     = "g"
BottomOfBuffer  = "G"

[insert]
