[global]
NormalMode      = "esc"
MoveLeft        = "left"
MoveDown        = "down"
MoveUp          = "up"
MoveRight       = "right"
Delete          = "x"

[normal]
MoveLeft        = "h"
MoveDown        = "j"
MoveUp          = "k"
MoveRight       = "l"
Append          = "a"
AppendLineEnd   = "A"
InsertLineStart = "I"
Write           = "W"
# Modes
ScrollMode      = "n"
InsertMode      = "i"
DeleteMode      = "d"
ChangeMode      = "c"

[scroll]
ScrollDown      = "j"
ScrollUp        = "k"
PageDown        = "J"
PageUp          = "K"
TopOfBuffer     = "g"
BottomOfBuffer  = "G"

[insert]

[delete]

[change]
