[info]
name = "Rust"
extension = "rs"

[syntax]
number = [ 
  '([0-9]+[0-9_]*)', 
  '(0x[a-f0-9_]+)' 
]
string = [ 
  '(".*?[^\\]")', 
  '''('.*?[^\\&<]')'''
]
comment = [ 
  '(//.*\n?)'
] # TODO: Block comment
fn-call = [ 
  '''(\w+)(?:\(|<)'''
]
class = [ 
  '([[:upper:]]\w+)'
] # REALLY lazy regex
keyword = [
  '\b(as|break|const|continue|else|enum|extern|fn|for|if|impl|in|let|loop|match|mod|move|mut|pub|ref|return|static|struct|super|trait|type|unsafe|use|where|while|async|await|dyn|union)\W'
]
keyword-alt = [ 
  '(self|true|false|crate|macro_rules|str|((?:u|i)(?:8|16|32|64|128|size))|(f(?:32|64))|bool)'
]
property = [ 
  '\w+\.(\w+)', 
  '(\w+!)\(.*\)', 
  '([[:lower:]]\w+)::', 
  '#\[(.*)\]',
  '(?:\(|\s{2,}|pub\s|,\s)\b(\w+):\s',
  '''(?:&|<)('\w+)''' 
]
